import { useMemo, useState } from "react";
import { zipSync } from "fflate";
import type { ARMode, ExperienceConfig } from "../types/experience";
import { buildPublishedUrl, buildStudioUrl, canGenerateQr } from "../lib/studio";
import { createQrDataUrl } from "../lib/qr";

const DEFAULT_IMAGE =
  "https://images.unsplash.com/photo-1556740749-887f6717d7e4?auto=format&fit=crop&w=900&q=85";
const DEFAULT_DESTINATION = "https://example.com/";

function downloadBlob(filename: string, value: BlobPart, type: string): void {
  const blob = new Blob([value], { type });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function dataUrlToBytes(dataUrl: string): Uint8Array {
  const base64 = dataUrl.split(",")[1] ?? "";
  const binary = atob(base64);
  return Uint8Array.from(binary, (char) => char.charCodeAt(0));
}

function extensionForFile(file: File): string {
  const subtype = file.type.split("/")[1]?.toLowerCase();
  return subtype === "jpeg"
    ? "jpg"
    : (subtype || "bin").replace(/[^a-z0-9]/g, "").slice(0, 8) || "bin";
}

export function Studio() {
  const [baseUrl, setBaseUrl] = useState(window.location.origin);
  const [config, setConfig] = useState<ExperienceConfig>({
    id: "menu-01",
    title: "Your AR Menu",
    subtitle: "Tap the floating image to continue.",
    imageUrl: "/experiences/menu-01/card.webp",
    destinationUrl: DEFAULT_DESTINATION,
    mode: "qr",
    theme: "editorial",
    ctaLabel: "Open menu",
    fallbackEnabled: true,
  });
  const [imagePreview, setImagePreview] = useState(DEFAULT_IMAGE);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [targetFile, setTargetFile] = useState<File | null>(null);
  const [qr, setQr] = useState("");
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");

  const publishedUrl = useMemo(
    () => buildPublishedUrl(baseUrl.trim().replace(/\/$/, ""), config.id || "experience"),
    [baseUrl, config.id],
  );

  const previewUrl = useMemo(
    () =>
      buildStudioUrl(window.location.origin, {
        ...config,
        imageUrl: imagePreview,
        id: config.id || "experience",
      }),
    [config, imagePreview],
  );

  const qrReady = canGenerateQr(config, publishedUrl);
  const canOpenQueryPreview = !imageFile && previewUrl.length <= 1800;

  function update<K extends keyof ExperienceConfig>(key: K, value: ExperienceConfig[K]) {
    setConfig((current) => ({ ...current, [key]: value }));
    setQr("");
    setError("");
    setStatus("");
  }

  async function generateQr() {
    if (!qrReady) {
      setError(
        "Use a valid public base URL, image URL/path, destination URL, and required target asset.",
      );
      setQr("");
      return;
    }

    try {
      setError("");
      setQr(await createQrDataUrl(publishedUrl));
      setStatus("QR generated with the compact /ar/<slug> URL.");
    } catch {
      setError("QR generation failed.");
    }
  }

  function handleImageFile(file: File | undefined) {
    if (!file) return;
    if (!file.type.startsWith("image/")) {
      setError("Please choose an image file.");
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result === "string") {
        const extension = extensionForFile(file);
        setImageFile(file);
        setImagePreview(reader.result);
        update("imageUrl", `/experiences/${config.id || "experience"}/card.${extension}`);
        setStatus("Image loaded. It will be included in the deployment ZIP.");
      }
    };
    reader.readAsDataURL(file);
  }

  function handleTargetFile(file: File | undefined) {
    if (!file) return;
    if (!file.name.toLowerCase().endsWith(".mind")) {
      setError(
        "Image-target mode requires a .mind file generated by the MindAR Target Compiler.",
      );
      return;
    }

    setTargetFile(file);
    update("targetUrl", `/experiences/${config.id || "experience"}/target.mind`);
    setStatus("MindAR target loaded. It will be included in the deployment ZIP.");
  }

  function downloadPack() {
    setError("");

    if (!imageFile) {
      setError("Upload the experience image before exporting a deployment ZIP.");
      return;
    }

    if (config.mode === "image-target" && !targetFile) {
      setError("Image-target mode needs the .mind target file.");
      return;
    }

    const slug = config.id.trim();
    if (!slug) {
      setError("Experience ID is required.");
      return;
    }

    const extension = extensionForFile(imageFile);
    const manifest: ExperienceConfig = {
      ...config,
      id: slug,
      imageUrl: `/experiences/${slug}/card.${extension}`,
      ...(config.mode === "image-target"
        ? { targetUrl: "/experiences/" + slug + "/target.mind" }
        : {}),
    };

    const baseEntries: Record<string, Uint8Array> = {
      [`public/experiences/${slug}/experience.json`]: new TextEncoder().encode(
        JSON.stringify(manifest, null, 2),
      ),
      "WEBTEA-AR-DEPLOY.txt": new TextEncoder().encode(
        [
          "WEBTEA AR DEPLOY PACK",
          "",
          "Experience: " + slug,
          "AR URL: " + publishedUrl,
          "",
          "Unzip this pack at the root of the webtea-ar repository.",
          "Then commit and deploy.",
          "The QR contains only the compact /ar/<slug> URL.",
          config.mode === "image-target"
            ? "Image-target mode includes target.mind."
            : "QR camera mode uses the camera feed with a floating interactive card.",
        ].join("\n"),
      ),
    };

    Promise.all([
      imageFile.arrayBuffer(),
      config.mode === "image-target" && targetFile
        ? targetFile.arrayBuffer()
        : Promise.resolve(null),
    ])
      .then(([imageBytes, targetBytes]) => {
        const entries = { ...baseEntries };
        entries[`public/experiences/${slug}/card.${extension}`] =
          new Uint8Array(imageBytes);

        if (targetBytes) {
          entries[`public/experiences/${slug}/target.mind`] =
            new Uint8Array(targetBytes);
        }

        if (qr) {
          entries[`public/qr/${slug}-qr.png`] = dataUrlToBytes(qr);
        }

        const archive = zipSync(entries, { level: 6 });
        downloadBlob(
          `${slug}-webtea-ar-deploy.zip`,
          archive,
          "application/zip",
        );
        setStatus(
          "Deployment ZIP generated. Unzip it at the repository root, commit, and deploy.",
        );
      })
      .catch(() => setError("Could not package the deployment ZIP."));
  }

  return (
    <main className="studio-shell">
      <div className="studio">
        <header>
          <p className="eyebrow">WEBTEA HQ · AR STUDIO</p>
          <h1>Build a QR → AR experience.</h1>
          <p className="home-card__copy">
            Upload the card image, attach the destination URL, generate a compact
            QR, and export a ready-to-deploy asset pack. Everything after
            deployment is static.
          </p>
        </header>

        <div className="studio-grid">
          <section className="panel">
            <h2>Experience setup</h2>

            <div className="field">
              <label htmlFor="base-url">Public base URL</label>
              <input
                id="base-url"
                type="url"
                placeholder="https://your-project.vercel.app"
                value={baseUrl}
                onChange={(e) => {
                  setBaseUrl(e.target.value);
                  setQr("");
                }}
              />
              <div className="note">
                Use the final HTTPS domain that will be printed in the QR code.
              </div>
            </div>

            <div className="field">
              <label htmlFor="experience-id">Experience ID</label>
              <input
                id="experience-id"
                value={config.id}
                onChange={(e) =>
                  update(
                    "id",
                    e.target.value.replace(/[^a-zA-Z0-9_-]/g, "-"),
                  )
                }
              />
            </div>

            <div className="field">
              <label htmlFor="title">Title</label>
              <input
                id="title"
                value={config.title}
                onChange={(e) => update("title", e.target.value)}
              />
            </div>

            <div className="field">
              <label htmlFor="subtitle">Subtitle</label>
              <input
                id="subtitle"
                value={config.subtitle ?? ""}
                onChange={(e) => update("subtitle", e.target.value)}
              />
            </div>

            <div className="field">
              <label htmlFor="destination">Destination URL</label>
              <input
                id="destination"
                type="url"
                placeholder="https://your-menu.com/"
                value={config.destinationUrl}
                onChange={(e) => update("destinationUrl", e.target.value)}
              />
            </div>

            <div className="field">
              <label>AR mode</label>
              <select
                value={config.mode}
                onChange={(e) =>
                  update("mode", e.target.value as ARMode)
                }
              >
                <option value="qr">QR camera AR · no target file</option>
                <option value="image-target">
                  Image-tracked AR · true tracking
                </option>
              </select>
            </div>

            <div className="field">
              <label htmlFor="image-file">Experience image</label>
              <div className="file-drop">
                <input
                  id="image-file"
                  type="file"
                  accept="image/*"
                  onChange={(e) => handleImageFile(e.target.files?.[0])}
                />
                <label htmlFor="image-file" className="ui-button">
                  Upload image
                </label>
                <div className="note">
                  {imageFile
                    ? imageFile.name
                    : "The uploaded image becomes the AR card inside the deployment pack."}
                </div>
              </div>
            </div>

            <div className="field">
              <label htmlFor="image-url">Or use a public image URL</label>
              <input
                id="image-url"
                type="url"
                value={imageFile ? "" : config.imageUrl}
                onChange={(e) => {
                  setImageFile(null);
                  setImagePreview(e.target.value || DEFAULT_IMAGE);
                  update("imageUrl", e.target.value);
                }}
              />
            </div>

            {config.mode === "image-target" ? (
              <div className="field">
                <label htmlFor="target-file">MindAR target (.mind)</label>
                <div className="file-drop">
                  <input
                    id="target-file"
                    type="file"
                    accept=".mind,application/octet-stream"
                    onChange={(e) => handleTargetFile(e.target.files?.[0])}
                  />
                  <label htmlFor="target-file" className="ui-button">
                    Upload .mind target
                  </label>
                  <div className="note">
                    {targetFile
                      ? targetFile.name
                      : "Generate it with the MindAR Target Compiler."}
                  </div>
                </div>
              </div>
            ) : null}

            <div className="home-links">
              <button
                className="ui-button ui-button--primary"
                type="button"
                onClick={generateQr}
                disabled={!qrReady}
              >
                Generate QR
              </button>
              <button
                className="ui-button"
                type="button"
                onClick={downloadPack}
                disabled={!imageFile}
              >
                Download deployment ZIP
              </button>
            </div>

            {status ? <p className="note">{status}</p> : null}
            {error ? <p className="error">{error}</p> : null}
          </section>

          <section className="panel">
            <h2>Preview & QR</h2>
            <div className="preview-stage">
              <img
                className="preview-card"
                src={imagePreview}
                alt="AR experience preview"
                onError={(event) => {
                  event.currentTarget.src = DEFAULT_IMAGE;
                }}
              />
            </div>

            <p className="note">Published URL</p>
            <div className="field">
              <input
                readOnly
                value={publishedUrl}
                aria-label="Published URL"
              />
            </div>

            <p className="note">
              Development query preview (not used for production QR)
            </p>
            <div className="field">
              <input
                readOnly
                value={previewUrl}
                aria-label="Query preview URL"
              />
            </div>

            {qr ? (
              <div className="qr-wrap">
                <img src={qr} alt="Generated QR code" />
                <a
                  className="ui-link"
                  href={qr}
                  download={`${config.id || "webtea-ar"}-qr.png`}
                >
                  Download QR PNG
                </a>
              </div>
            ) : (
              <p className="note">
                The production QR encodes only <code>/ar/&lt;slug&gt;</code>, keeping
                the printed code compact and durable.
              </p>
            )}

            {canOpenQueryPreview ? (
              <a
                className="ui-link"
                href={previewUrl}
                target="_blank"
                rel="noreferrer"
              >
                Open query preview
              </a>
            ) : (
              <p className="note">
                Local image preview cannot be opened as a share URL; use the
                deployment ZIP and the published URL after deployment.
              </p>
            )}
          </section>
        </div>
      </div>
    </main>
  );
}
